from dataclasses import dataclass, field
from typing import List, Optional


@dataclass
class Song:
    title: str
    artist: str
    genre: str
    mood: str
    themes: List[str] = field(default_factory=list)
    lyrics_excerpt: str = ""
    # Audio features on a 0.0-1.0 scale, compared against the taste-affinity
    # model's predicted target profile (see taste_model.py). Default to a
    # neutral midpoint for songs whose audio features aren't known.
    energy: float = 0.5
    valence: float = 0.5
    acousticness: float = 0.5
    # Additional attributes generated by an agentic AI workflow (see
    # scripts/generate_song_attributes.py and music_recommender/song_attributes.py).
    # Optional/empty by default so songs without generated attributes still work.
    popularity: Optional[int] = None  # 0-100, Claude's estimate of mainstream familiarity
    release_decade: Optional[str] = None  # e.g. "2020s"
    detailed_mood_tags: List[str] = field(default_factory=list)  # finer-grained than `mood`
    vocal_style: Optional[str] = None
    instrumentation_notes: Optional[str] = None


@dataclass
class TasteProfile:
    name: str
    preferred_genres: List[str]
    preferred_moods: List[str]
    preferred_themes: List[str]
    favorite_artists: List[str]


@dataclass
class Recommendation:
    title: str
    artist: str
    genre: str
    score: float
    explanation: str
